### ISSUE TITLE
Asignar el equipo "Admins" a este repo

### ISSUE THREAD

**Issue by eruizdechavez** [codersmexico/chilangobot#1]
Para facilitar la colaboración, configuración, etc. el resto del equipo necesita tener acceso a este repo.

@poguez please en la configuracion del repo asigna el Team "Admins" con los permisos correctos.

**Comment by poguez** [comment]
Done ✅.

**Comment by eruizdechavez** [comment]
Sigo sin ver el tab de settings 😢 

<img width="805" alt="screen shot 2017-05-09 at 11 26 52 am" src="https://cloud.githubusercontent.com/assets/953140/25861500/8dbe0e4c-34aa-11e7-8fad-34c4d7b24f78.png">
